version: "3"

services:
  sonarqube:
    image: sonarqube:7.9.5-community
    depends_on:
      - init
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/sonarqube
      SONARQUBE_JDBC_USERNAME: sonarqube
      SONARQUBE_JDBC_PASSWORD: password
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ulimits:
      nproc: 131072
      nofile:
        soft: 8192
        hard: 131072
    ports:
      - "9000:9000"
  init:
    image: bash
    privileged: true
    user: root
    volumes:
      - /c/Users/Zach/dockerStuff/init.sh:/mnt/init.sh
    command: ["sh", "-e", "/mnt/init.sh"]
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
